namespace Yomicchi.Core
{
    public partial class Deinflector
    {
        public static List<Rule> Rules =
        [
            new Rule("-ba", [
                new RuleVariant("ければ", "い", RuleType.None, RuleType.adji),
                new RuleVariant("えば", "う", RuleType.None, RuleType.v5),
                new RuleVariant("けば", "く", RuleType.None, RuleType.v5),
                new RuleVariant("げば", "ぐ", RuleType.None, RuleType.v5),
                new RuleVariant("せば", "す", RuleType.None, RuleType.v5),
                new RuleVariant("てば", "つ", RuleType.None, RuleType.v5),
                new RuleVariant("ねば", "ぬ", RuleType.None, RuleType.v5),
                new RuleVariant("べば", "ぶ", RuleType.None, RuleType.v5),
                new RuleVariant("めば", "む", RuleType.None, RuleType.v5),
                new RuleVariant("れば", "る", RuleType.None, RuleType.v1 | RuleType.v5 | RuleType.vk | RuleType.vs | RuleType.vz)
            ]),
            new Rule("-chau", [
                new RuleVariant("ちゃう", "る", RuleType.v5, RuleType.v1),
                new RuleVariant("いじゃう", "ぐ", RuleType.v5, RuleType.v5),
                new RuleVariant("いちゃう", "く", RuleType.v5, RuleType.v5),
                new RuleVariant("しちゃう", "す", RuleType.v5, RuleType.v5),
                new RuleVariant("っちゃう", "う", RuleType.v5, RuleType.v5),
                new RuleVariant("っちゃう", "く", RuleType.v5, RuleType.v5),
                new RuleVariant("っちゃう", "つ", RuleType.v5, RuleType.v5),
                new RuleVariant("っちゃう", "る", RuleType.v5, RuleType.v5),
                new RuleVariant("んじゃう", "ぬ", RuleType.v5, RuleType.v5),
                new RuleVariant("んじゃう", "ぶ", RuleType.v5, RuleType.v5),
                new RuleVariant("んじゃう", "む", RuleType.v5, RuleType.v5),
                new RuleVariant("じちゃう", "ずる", RuleType.v5, RuleType.vz),
                new RuleVariant("しちゃう", "する", RuleType.v5, RuleType.vs),
                new RuleVariant("為ちゃう", "為る", RuleType.v5, RuleType.vs),
                new RuleVariant("きちゃう", "くる", RuleType.v5, RuleType.vk),
                new RuleVariant("来ちゃう", "来る", RuleType.v5, RuleType.vk),
                new RuleVariant("來ちゃう", "來る", RuleType.v5, RuleType.vk)
            ]),
            new Rule("-chimau", [
                new RuleVariant("ちまう", "る", RuleType.v5, RuleType.v1),
                new RuleVariant("いじまう", "ぐ", RuleType.v5, RuleType.v5),
                new RuleVariant("いちまう", "く", RuleType.v5, RuleType.v5),
                new RuleVariant("しちまう", "す", RuleType.v5, RuleType.v5),
                new RuleVariant("っちまう", "う", RuleType.v5, RuleType.v5),
                new RuleVariant("っちまう", "く", RuleType.v5, RuleType.v5),
                new RuleVariant("っちまう", "つ", RuleType.v5, RuleType.v5),
                new RuleVariant("っちまう", "る", RuleType.v5, RuleType.v5),
                new RuleVariant("んじまう", "ぬ", RuleType.v5, RuleType.v5),
                new RuleVariant("んじまう", "ぶ", RuleType.v5, RuleType.v5),
                new RuleVariant("んじまう", "む", RuleType.v5, RuleType.v5),
                new RuleVariant("じちまう", "ずる", RuleType.v5, RuleType.vz),
                new RuleVariant("しちまう", "する", RuleType.v5, RuleType.vs),
                new RuleVariant("為ちまう", "為る", RuleType.v5, RuleType.vs),
                new RuleVariant("きちまう", "くる", RuleType.v5, RuleType.vk),
                new RuleVariant("来ちまう", "来る", RuleType.v5, RuleType.vk),
                new RuleVariant("來ちまう", "來る", RuleType.v5, RuleType.vk)
            ]),
            new Rule("-shimau", [
                new RuleVariant("てしまう", "て", RuleType.v5, RuleType.iru),
                new RuleVariant("でしまう", "で", RuleType.v5, RuleType.iru)
            ]),
            new Rule("-nasai", [
                new RuleVariant("なさい", "る", RuleType.None, RuleType.v1),
                new RuleVariant("いなさい", "う", RuleType.None, RuleType.v5),
                new RuleVariant("きなさい", "く", RuleType.None, RuleType.v5),
                new RuleVariant("ぎなさい", "ぐ", RuleType.None, RuleType.v5),
                new RuleVariant("しなさい", "す", RuleType.None, RuleType.v5),
                new RuleVariant("ちなさい", "つ", RuleType.None, RuleType.v5),
                new RuleVariant("になさい", "ぬ", RuleType.None, RuleType.v5),
                new RuleVariant("びなさい", "ぶ", RuleType.None, RuleType.v5),
                new RuleVariant("みなさい", "む", RuleType.None, RuleType.v5),
                new RuleVariant("りなさい", "る", RuleType.None, RuleType.v5),
                new RuleVariant("じなさい", "ずる", RuleType.None, RuleType.vz),
                new RuleVariant("しなさい", "する", RuleType.None, RuleType.vs),
                new RuleVariant("為なさい", "為る", RuleType.None, RuleType.vs),
                new RuleVariant("きなさい", "くる", RuleType.None, RuleType.vk),
                new RuleVariant("来なさい", "来る", RuleType.None, RuleType.vk),
                new RuleVariant("來なさい", "來る", RuleType.None, RuleType.vk)
            ]),
            new Rule("-sou", [
                new RuleVariant("そう", "い", RuleType.None, RuleType.adji),
                new RuleVariant("そう", "る", RuleType.None, RuleType.v1),
                new RuleVariant("いそう", "う", RuleType.None, RuleType.v5),
                new RuleVariant("きそう", "く", RuleType.None, RuleType.v5),
                new RuleVariant("ぎそう", "ぐ", RuleType.None, RuleType.v5),
                new RuleVariant("しそう", "す", RuleType.None, RuleType.v5),
                new RuleVariant("ちそう", "つ", RuleType.None, RuleType.v5),
                new RuleVariant("にそう", "ぬ", RuleType.None, RuleType.v5),
                new RuleVariant("びそう", "ぶ", RuleType.None, RuleType.v5),
                new RuleVariant("みそう", "む", RuleType.None, RuleType.v5),
                new RuleVariant("りそう", "る", RuleType.None, RuleType.v5),
                new RuleVariant("じそう", "ずる", RuleType.None, RuleType.vz),
                new RuleVariant("しそう", "する", RuleType.None, RuleType.vs),
                new RuleVariant("為そう", "為る", RuleType.None, RuleType.vs),
                new RuleVariant("きそう", "くる", RuleType.None, RuleType.vk),
                new RuleVariant("来そう", "来る", RuleType.None, RuleType.vk),
                new RuleVariant("來そう", "來る", RuleType.None, RuleType.vk)
            ]),
            new Rule("-sugiru", [
                new RuleVariant("すぎる", "い", RuleType.v1, RuleType.adji),
                new RuleVariant("すぎる", "る", RuleType.v1, RuleType.v1),
                new RuleVariant("いすぎる", "う", RuleType.v1, RuleType.v5),
                new RuleVariant("きすぎる", "く", RuleType.v1, RuleType.v5),
                new RuleVariant("ぎすぎる", "ぐ", RuleType.v1, RuleType.v5),
                new RuleVariant("しすぎる", "す", RuleType.v1, RuleType.v5),
                new RuleVariant("ちすぎる", "つ", RuleType.v1, RuleType.v5),
                new RuleVariant("にすぎる", "ぬ", RuleType.v1, RuleType.v5),
                new RuleVariant("びすぎる", "ぶ", RuleType.v1, RuleType.v5),
                new RuleVariant("みすぎる", "む", RuleType.v1, RuleType.v5),
                new RuleVariant("りすぎる", "る", RuleType.v1, RuleType.v5),
                new RuleVariant("じすぎる", "ずる", RuleType.v1, RuleType.vz),
                new RuleVariant("しすぎる", "する", RuleType.v1, RuleType.vs),
                new RuleVariant("為すぎる", "為る", RuleType.v1, RuleType.vs),
                new RuleVariant("きすぎる", "くる", RuleType.v1, RuleType.vk),
                new RuleVariant("来すぎる", "来る", RuleType.v1, RuleType.vk),
                new RuleVariant("來すぎる", "來る", RuleType.v1, RuleType.vk)
            ]),
            new Rule("-tai", [
                new RuleVariant("たい", "る", RuleType.adji, RuleType.v1),
                new RuleVariant("いたい", "う", RuleType.adji, RuleType.v5),
                new RuleVariant("きたい", "く", RuleType.adji, RuleType.v5),
                new RuleVariant("ぎたい", "ぐ", RuleType.adji, RuleType.v5),
                new RuleVariant("したい", "す", RuleType.adji, RuleType.v5),
                new RuleVariant("ちたい", "つ", RuleType.adji, RuleType.v5),
                new RuleVariant("にたい", "ぬ", RuleType.adji, RuleType.v5),
                new RuleVariant("びたい", "ぶ", RuleType.adji, RuleType.v5),
                new RuleVariant("みたい", "む", RuleType.adji, RuleType.v5),
                new RuleVariant("りたい", "る", RuleType.adji, RuleType.v5),
                new RuleVariant("じたい", "ずる", RuleType.adji, RuleType.vz),
                new RuleVariant("したい", "する", RuleType.adji, RuleType.vs),
                new RuleVariant("為たい", "為る", RuleType.adji, RuleType.vs),
                new RuleVariant("きたい", "くる", RuleType.adji, RuleType.vk),
                new RuleVariant("来たい", "来る", RuleType.adji, RuleType.vk),
                new RuleVariant("來たい", "來る", RuleType.adji, RuleType.vk)
            ]),
            new Rule("-tara", [
                new RuleVariant("かったら", "い", RuleType.None, RuleType.adji),
                new RuleVariant("たら", "る", RuleType.None, RuleType.v1),
                new RuleVariant("いたら", "く", RuleType.None, RuleType.v5),
                new RuleVariant("いだら", "ぐ", RuleType.None, RuleType.v5),
                new RuleVariant("したら", "す", RuleType.None, RuleType.v5),
                new RuleVariant("ったら", "う", RuleType.None, RuleType.v5),
                new RuleVariant("ったら", "つ", RuleType.None, RuleType.v5),
                new RuleVariant("ったら", "る", RuleType.None, RuleType.v5),
                new RuleVariant("んだら", "ぬ", RuleType.None, RuleType.v5),
                new RuleVariant("んだら", "ぶ", RuleType.None, RuleType.v5),
                new RuleVariant("んだら", "む", RuleType.None, RuleType.v5),
                new RuleVariant("じたら", "ずる", RuleType.None, RuleType.vz),
                new RuleVariant("したら", "する", RuleType.None, RuleType.vs),
                new RuleVariant("為たら", "為る", RuleType.None, RuleType.vs),
                new RuleVariant("きたら", "くる", RuleType.None, RuleType.vk),
                new RuleVariant("来たら", "来る", RuleType.None, RuleType.vk),
                new RuleVariant("來たら", "來る", RuleType.None, RuleType.vk),
                new RuleVariant("いったら", "いく", RuleType.None, RuleType.v5),
                new RuleVariant("おうたら", "おう", RuleType.None, RuleType.v5),
                new RuleVariant("こうたら", "こう", RuleType.None, RuleType.v5),
                new RuleVariant("そうたら", "そう", RuleType.None, RuleType.v5),
                new RuleVariant("とうたら", "とう", RuleType.None, RuleType.v5),
                new RuleVariant("行ったら", "行く", RuleType.None, RuleType.v5),
                new RuleVariant("逝ったら", "逝く", RuleType.None, RuleType.v5),
                new RuleVariant("往ったら", "往く", RuleType.None, RuleType.v5),
                new RuleVariant("請うたら", "請う", RuleType.None, RuleType.v5),
                new RuleVariant("乞うたら", "乞う", RuleType.None, RuleType.v5),
                new RuleVariant("恋うたら", "恋う", RuleType.None, RuleType.v5),
                new RuleVariant("問うたら", "問う", RuleType.None, RuleType.v5),
                new RuleVariant("負うたら", "負う", RuleType.None, RuleType.v5),
                new RuleVariant("沿うたら", "沿う", RuleType.None, RuleType.v5),
                new RuleVariant("添うたら", "添う", RuleType.None, RuleType.v5),
                new RuleVariant("副うたら", "副う", RuleType.None, RuleType.v5),
                new RuleVariant("厭うたら", "厭う", RuleType.None, RuleType.v5),
                new RuleVariant("のたもうたら", "のたまう", RuleType.None, RuleType.v5)
            ]),
            new Rule("-tari", [
                new RuleVariant("かったり", "い", RuleType.None, RuleType.adji),
                new RuleVariant("たり", "る", RuleType.None, RuleType.v1),
                new RuleVariant("いたり", "く", RuleType.None, RuleType.v5),
                new RuleVariant("いだり", "ぐ", RuleType.None, RuleType.v5),
                new RuleVariant("したり", "す", RuleType.None, RuleType.v5),
                new RuleVariant("ったり", "う", RuleType.None, RuleType.v5),
                new RuleVariant("ったり", "つ", RuleType.None, RuleType.v5),
                new RuleVariant("ったり", "る", RuleType.None, RuleType.v5),
                new RuleVariant("んだり", "ぬ", RuleType.None, RuleType.v5),
                new RuleVariant("んだり", "ぶ", RuleType.None, RuleType.v5),
                new RuleVariant("んだり", "む", RuleType.None, RuleType.v5),
                new RuleVariant("じたり", "ずる", RuleType.None, RuleType.vz),
                new RuleVariant("したり", "する", RuleType.None, RuleType.vs),
                new RuleVariant("為たり", "為る", RuleType.None, RuleType.vs),
                new RuleVariant("きたり", "くる", RuleType.None, RuleType.vk),
                new RuleVariant("来たり", "来る", RuleType.None, RuleType.vk),
                new RuleVariant("來たり", "來る", RuleType.None, RuleType.vk),
                new RuleVariant("いったり", "いく", RuleType.None, RuleType.v5),
                new RuleVariant("おうたり", "おう", RuleType.None, RuleType.v5),
                new RuleVariant("こうたり", "こう", RuleType.None, RuleType.v5),
                new RuleVariant("そうたり", "そう", RuleType.None, RuleType.v5),
                new RuleVariant("とうたり", "とう", RuleType.None, RuleType.v5),
                new RuleVariant("行ったり", "行く", RuleType.None, RuleType.v5),
                new RuleVariant("逝ったり", "逝く", RuleType.None, RuleType.v5),
                new RuleVariant("往ったり", "往く", RuleType.None, RuleType.v5),
                new RuleVariant("請うたり", "請う", RuleType.None, RuleType.v5),
                new RuleVariant("乞うたり", "乞う", RuleType.None, RuleType.v5),
                new RuleVariant("恋うたり", "恋う", RuleType.None, RuleType.v5),
                new RuleVariant("問うたり", "問う", RuleType.None, RuleType.v5),
                new RuleVariant("負うたり", "負う", RuleType.None, RuleType.v5),
                new RuleVariant("沿うたり", "沿う", RuleType.None, RuleType.v5),
                new RuleVariant("添うたり", "添う", RuleType.None, RuleType.v5),
                new RuleVariant("副うたり", "副う", RuleType.None, RuleType.v5),
                new RuleVariant("厭うたり", "厭う", RuleType.None, RuleType.v5),
                new RuleVariant("のたもうたり", "のたまう", RuleType.None, RuleType.v5)
            ]),
            new Rule("-te", [
                new RuleVariant("くて", "い", RuleType.iru, RuleType.adji),
                new RuleVariant("て", "る", RuleType.iru, RuleType.v1),
                new RuleVariant("いて", "く", RuleType.iru, RuleType.v5),
                new RuleVariant("いで", "ぐ", RuleType.iru, RuleType.v5),
                new RuleVariant("して", "す", RuleType.iru, RuleType.v5),
                new RuleVariant("って", "う", RuleType.iru, RuleType.v5),
                new RuleVariant("って", "つ", RuleType.iru, RuleType.v5),
                new RuleVariant("って", "る", RuleType.iru, RuleType.v5),
                new RuleVariant("んで", "ぬ", RuleType.iru, RuleType.v5),
                new RuleVariant("んで", "ぶ", RuleType.iru, RuleType.v5),
                new RuleVariant("んで", "む", RuleType.iru, RuleType.v5),
                new RuleVariant("じて", "ずる", RuleType.iru, RuleType.vz),
                new RuleVariant("して", "する", RuleType.iru, RuleType.vs),
                new RuleVariant("為て", "為る", RuleType.iru, RuleType.vs),
                new RuleVariant("きて", "くる", RuleType.iru, RuleType.vk),
                new RuleVariant("来て", "来る", RuleType.iru, RuleType.vk),
                new RuleVariant("來て", "來る", RuleType.iru, RuleType.vk),
                new RuleVariant("いって", "いく", RuleType.iru, RuleType.v5),
                new RuleVariant("おうて", "おう", RuleType.iru, RuleType.v5),
                new RuleVariant("こうて", "こう", RuleType.iru, RuleType.v5),
                new RuleVariant("そうて", "そう", RuleType.iru, RuleType.v5),
                new RuleVariant("とうて", "とう", RuleType.iru, RuleType.v5),
                new RuleVariant("行って", "行く", RuleType.iru, RuleType.v5),
                new RuleVariant("逝って", "逝く", RuleType.iru, RuleType.v5),
                new RuleVariant("往って", "往く", RuleType.iru, RuleType.v5),
                new RuleVariant("請うて", "請う", RuleType.iru, RuleType.v5),
                new RuleVariant("乞うて", "乞う", RuleType.iru, RuleType.v5),
                new RuleVariant("恋うて", "恋う", RuleType.iru, RuleType.v5),
                new RuleVariant("問うて", "問う", RuleType.iru, RuleType.v5),
                new RuleVariant("負うて", "負う", RuleType.iru, RuleType.v5),
                new RuleVariant("沿うて", "沿う", RuleType.iru, RuleType.v5),
                new RuleVariant("添うて", "添う", RuleType.iru, RuleType.v5),
                new RuleVariant("副うて", "副う", RuleType.iru, RuleType.v5),
                new RuleVariant("厭うて", "厭う", RuleType.iru, RuleType.v5),
                new RuleVariant("のたもうて", "のたまう", RuleType.iru, RuleType.v5)
            ]),
            new Rule("-zu", [
                new RuleVariant("ず", "る", RuleType.None, RuleType.v1),
                new RuleVariant("かず", "く", RuleType.None, RuleType.v5),
                new RuleVariant("がず", "ぐ", RuleType.None, RuleType.v5),
                new RuleVariant("さず", "す", RuleType.None, RuleType.v5),
                new RuleVariant("たず", "つ", RuleType.None, RuleType.v5),
                new RuleVariant("なず", "ぬ", RuleType.None, RuleType.v5),
                new RuleVariant("ばず", "ぶ", RuleType.None, RuleType.v5),
                new RuleVariant("まず", "む", RuleType.None, RuleType.v5),
                new RuleVariant("らず", "る", RuleType.None, RuleType.v5),
                new RuleVariant("わず", "う", RuleType.None, RuleType.v5),
                new RuleVariant("ぜず", "ずる", RuleType.None, RuleType.vz),
                new RuleVariant("せず", "する", RuleType.None, RuleType.vs),
                new RuleVariant("為ず", "為る", RuleType.None, RuleType.vs),
                new RuleVariant("こず", "くる", RuleType.None, RuleType.vk),
                new RuleVariant("来ず", "来る", RuleType.None, RuleType.vk),
                new RuleVariant("來ず", "來る", RuleType.None, RuleType.vk)
            ]),
            new Rule("-nu", [
                new RuleVariant("ぬ", "る", RuleType.None, RuleType.v1),
                new RuleVariant("かぬ", "く", RuleType.None, RuleType.v5),
                new RuleVariant("がぬ", "ぐ", RuleType.None, RuleType.v5),
                new RuleVariant("さぬ", "す", RuleType.None, RuleType.v5),
                new RuleVariant("たぬ", "つ", RuleType.None, RuleType.v5),
                new RuleVariant("なぬ", "ぬ", RuleType.None, RuleType.v5),
                new RuleVariant("ばぬ", "ぶ", RuleType.None, RuleType.v5),
                new RuleVariant("まぬ", "む", RuleType.None, RuleType.v5),
                new RuleVariant("らぬ", "る", RuleType.None, RuleType.v5),
                new RuleVariant("わぬ", "う", RuleType.None, RuleType.v5),
                new RuleVariant("ぜぬ", "ずる", RuleType.None, RuleType.vz),
                new RuleVariant("せぬ", "する", RuleType.None, RuleType.vs),
                new RuleVariant("為ぬ", "為る", RuleType.None, RuleType.vs),
                new RuleVariant("こぬ", "くる", RuleType.None, RuleType.vk),
                new RuleVariant("来ぬ", "来る", RuleType.None, RuleType.vk),
                new RuleVariant("來ぬ", "來る", RuleType.None, RuleType.vk)
            ]),
            new Rule("adv", [
                new RuleVariant("く", "い", RuleType.None, RuleType.adji)
            ]),
            new Rule("causative", [
                new RuleVariant("させる", "る", RuleType.v1, RuleType.v1),
                new RuleVariant("かせる", "く", RuleType.v1, RuleType.v5),
                new RuleVariant("がせる", "ぐ", RuleType.v1, RuleType.v5),
                new RuleVariant("させる", "す", RuleType.v1, RuleType.v5),
                new RuleVariant("たせる", "つ", RuleType.v1, RuleType.v5),
                new RuleVariant("なせる", "ぬ", RuleType.v1, RuleType.v5),
                new RuleVariant("ばせる", "ぶ", RuleType.v1, RuleType.v5),
                new RuleVariant("ませる", "む", RuleType.v1, RuleType.v5),
                new RuleVariant("らせる", "る", RuleType.v1, RuleType.v5),
                new RuleVariant("わせる", "う", RuleType.v1, RuleType.v5),
                new RuleVariant("じさせる", "ずる", RuleType.v1, RuleType.vz),
                new RuleVariant("ぜさせる", "ずる", RuleType.v1, RuleType.vz),
                new RuleVariant("させる", "する", RuleType.v1, RuleType.vs),
                new RuleVariant("為せる", "為る", RuleType.v1, RuleType.vs),
                new RuleVariant("せさせる", "する", RuleType.v1, RuleType.vs),
                new RuleVariant("為させる", "為る", RuleType.v1, RuleType.vs),
                new RuleVariant("こさせる", "くる", RuleType.v1, RuleType.vk),
                new RuleVariant("来させる", "来る", RuleType.v1, RuleType.vk),
                new RuleVariant("來させる", "來る", RuleType.v1, RuleType.vk)
            ]),
            new Rule("imperative", [
                new RuleVariant("ろ", "る", RuleType.None, RuleType.v1),
                new RuleVariant("よ", "る", RuleType.None, RuleType.v1),
                new RuleVariant("え", "う", RuleType.None, RuleType.v5),
                new RuleVariant("け", "く", RuleType.None, RuleType.v5),
                new RuleVariant("げ", "ぐ", RuleType.None, RuleType.v5),
                new RuleVariant("せ", "す", RuleType.None, RuleType.v5),
                new RuleVariant("て", "つ", RuleType.None, RuleType.v5),
                new RuleVariant("ね", "ぬ", RuleType.None, RuleType.v5),
                new RuleVariant("べ", "ぶ", RuleType.None, RuleType.v5),
                new RuleVariant("め", "む", RuleType.None, RuleType.v5),
                new RuleVariant("れ", "る", RuleType.None, RuleType.v5),
                new RuleVariant("じろ", "ずる", RuleType.None, RuleType.vz),
                new RuleVariant("ぜよ", "ずる", RuleType.None, RuleType.vz),
                new RuleVariant("しろ", "する", RuleType.None, RuleType.vs),
                new RuleVariant("せよ", "する", RuleType.None, RuleType.vs),
                new RuleVariant("為ろ", "為る", RuleType.None, RuleType.vs),
                new RuleVariant("為よ", "為る", RuleType.None, RuleType.vs),
                new RuleVariant("こい", "くる", RuleType.None, RuleType.vk),
                new RuleVariant("来い", "来る", RuleType.None, RuleType.vk),
                new RuleVariant("來い", "來る", RuleType.None, RuleType.vk)
            ]),
            new Rule("imperative negative", [
                new RuleVariant("な", "", RuleType.None, RuleType.v1 | RuleType.v5 | RuleType.vk | RuleType.vs | RuleType.vz)
            ]),
            new Rule("masu stem", [
                new RuleVariant("い", "いる", RuleType.None, RuleType.v1),
                new RuleVariant("え", "える", RuleType.None, RuleType.v1),
                new RuleVariant("き", "きる", RuleType.None, RuleType.v1),
                new RuleVariant("ぎ", "ぎる", RuleType.None, RuleType.v1),
                new RuleVariant("け", "ける", RuleType.None, RuleType.v1),
                new RuleVariant("げ", "げる", RuleType.None, RuleType.v1),
                new RuleVariant("じ", "じる", RuleType.None, RuleType.v1),
                new RuleVariant("せ", "せる", RuleType.None, RuleType.v1),
                new RuleVariant("ぜ", "ぜる", RuleType.None, RuleType.v1),
                new RuleVariant("ち", "ちる", RuleType.None, RuleType.v1),
                new RuleVariant("て", "てる", RuleType.None, RuleType.v1),
                new RuleVariant("で", "でる", RuleType.None, RuleType.v1),
                new RuleVariant("に", "にる", RuleType.None, RuleType.v1),
                new RuleVariant("ね", "ねる", RuleType.None, RuleType.v1),
                new RuleVariant("ひ", "ひる", RuleType.None, RuleType.v1),
                new RuleVariant("び", "びる", RuleType.None, RuleType.v1),
                new RuleVariant("へ", "へる", RuleType.None, RuleType.v1),
                new RuleVariant("べ", "べる", RuleType.None, RuleType.v1),
                new RuleVariant("み", "みる", RuleType.None, RuleType.v1),
                new RuleVariant("め", "める", RuleType.None, RuleType.v1),
                new RuleVariant("り", "りる", RuleType.None, RuleType.v1),
                new RuleVariant("れ", "れる", RuleType.None, RuleType.v1),
                new RuleVariant("い", "う", RuleType.None, RuleType.v5),
                new RuleVariant("き", "く", RuleType.None, RuleType.v5),
                new RuleVariant("ぎ", "ぐ", RuleType.None, RuleType.v5),
                new RuleVariant("し", "す", RuleType.None, RuleType.v5),
                new RuleVariant("ち", "つ", RuleType.None, RuleType.v5),
                new RuleVariant("に", "ぬ", RuleType.None, RuleType.v5),
                new RuleVariant("び", "ぶ", RuleType.None, RuleType.v5),
                new RuleVariant("み", "む", RuleType.None, RuleType.v5),
                new RuleVariant("り", "る", RuleType.None, RuleType.v5),
                new RuleVariant("き", "くる", RuleType.None, RuleType.vk),
                new RuleVariant("来", "来る", RuleType.None, RuleType.vk),
                new RuleVariant("來", "來る", RuleType.None, RuleType.vk)
            ]),
            new Rule("negative", [
                new RuleVariant("くない", "い", RuleType.adji, RuleType.adji),
                new RuleVariant("ない", "る", RuleType.adji, RuleType.v1),
                new RuleVariant("かない", "く", RuleType.adji, RuleType.v5),
                new RuleVariant("がない", "ぐ", RuleType.adji, RuleType.v5),
                new RuleVariant("さない", "す", RuleType.adji, RuleType.v5),
                new RuleVariant("たない", "つ", RuleType.adji, RuleType.v5),
                new RuleVariant("なない", "ぬ", RuleType.adji, RuleType.v5),
                new RuleVariant("ばない", "ぶ", RuleType.adji, RuleType.v5),
                new RuleVariant("まない", "む", RuleType.adji, RuleType.v5),
                new RuleVariant("らない", "る", RuleType.adji, RuleType.v5),
                new RuleVariant("わない", "う", RuleType.adji, RuleType.v5),
                new RuleVariant("じない", "ずる", RuleType.adji, RuleType.vz),
                new RuleVariant("しない", "する", RuleType.adji, RuleType.vs),
                new RuleVariant("為ない", "為る", RuleType.adji, RuleType.vs),
                new RuleVariant("こない", "くる", RuleType.adji, RuleType.vk),
                new RuleVariant("来ない", "来る", RuleType.adji, RuleType.vk),
                new RuleVariant("來ない", "來る", RuleType.adji, RuleType.vk)
            ]),
            new Rule("noun", [
                new RuleVariant("さ", "い", RuleType.None, RuleType.adji)
            ]),
            new Rule("passive", [
                new RuleVariant("かれる", "く", RuleType.v1, RuleType.v5),
                new RuleVariant("がれる", "ぐ", RuleType.v1, RuleType.v5),
                new RuleVariant("される", "す", RuleType.v1, RuleType.v5),
                new RuleVariant("たれる", "つ", RuleType.v1, RuleType.v5),
                new RuleVariant("なれる", "ぬ", RuleType.v1, RuleType.v5),
                new RuleVariant("ばれる", "ぶ", RuleType.v1, RuleType.v5),
                new RuleVariant("まれる", "む", RuleType.v1, RuleType.v5),
                new RuleVariant("われる", "う", RuleType.v1, RuleType.v5),
                new RuleVariant("られる", "る", RuleType.v1, RuleType.v5),
                new RuleVariant("じされる", "ずる", RuleType.v1, RuleType.vz),
                new RuleVariant("ぜされる", "ずる", RuleType.v1, RuleType.vz),
                new RuleVariant("される", "する", RuleType.v1, RuleType.vs),
                new RuleVariant("為れる", "為る", RuleType.v1, RuleType.vs),
                new RuleVariant("こられる", "くる", RuleType.v1, RuleType.vk),
                new RuleVariant("来られる", "来る", RuleType.v1, RuleType.vk),
                new RuleVariant("來られる", "來る", RuleType.v1, RuleType.vk)
            ]),
            new Rule("past", [
                new RuleVariant("かった", "い", RuleType.None, RuleType.adji),
                new RuleVariant("た", "る", RuleType.None, RuleType.v1),
                new RuleVariant("いた", "く", RuleType.None, RuleType.v5),
                new RuleVariant("いだ", "ぐ", RuleType.None, RuleType.v5),
                new RuleVariant("した", "す", RuleType.None, RuleType.v5),
                new RuleVariant("った", "う", RuleType.None, RuleType.v5),
                new RuleVariant("った", "つ", RuleType.None, RuleType.v5),
                new RuleVariant("った", "る", RuleType.None, RuleType.v5),
                new RuleVariant("んだ", "ぬ", RuleType.None, RuleType.v5),
                new RuleVariant("んだ", "ぶ", RuleType.None, RuleType.v5),
                new RuleVariant("んだ", "む", RuleType.None, RuleType.v5),
                new RuleVariant("じた", "ずる", RuleType.None, RuleType.vz),
                new RuleVariant("した", "する", RuleType.None, RuleType.vs),
                new RuleVariant("為た", "為る", RuleType.None, RuleType.vs),
                new RuleVariant("きた", "くる", RuleType.None, RuleType.vk),
                new RuleVariant("来た", "来る", RuleType.None, RuleType.vk),
                new RuleVariant("來た", "來る", RuleType.None, RuleType.vk),
                new RuleVariant("いった", "いく", RuleType.None, RuleType.v5),
                new RuleVariant("おうた", "おう", RuleType.None, RuleType.v5),
                new RuleVariant("こうた", "こう", RuleType.None, RuleType.v5),
                new RuleVariant("そうた", "そう", RuleType.None, RuleType.v5),
                new RuleVariant("とうた", "とう", RuleType.None, RuleType.v5),
                new RuleVariant("行った", "行く", RuleType.None, RuleType.v5),
                new RuleVariant("逝った", "逝く", RuleType.None, RuleType.v5),
                new RuleVariant("往った", "往く", RuleType.None, RuleType.v5),
                new RuleVariant("請うた", "請う", RuleType.None, RuleType.v5),
                new RuleVariant("乞うた", "乞う", RuleType.None, RuleType.v5),
                new RuleVariant("恋うた", "恋う", RuleType.None, RuleType.v5),
                new RuleVariant("問うた", "問う", RuleType.None, RuleType.v5),
                new RuleVariant("負うた", "負う", RuleType.None, RuleType.v5),
                new RuleVariant("沿うた", "沿う", RuleType.None, RuleType.v5),
                new RuleVariant("添うた", "添う", RuleType.None, RuleType.v5),
                new RuleVariant("副うた", "副う", RuleType.None, RuleType.v5),
                new RuleVariant("厭うた", "厭う", RuleType.None, RuleType.v5),
                new RuleVariant("のたもうた", "のたまう", RuleType.None, RuleType.v5)
            ]),
            new Rule("polite", [
                new RuleVariant("ます", "る", RuleType.None, RuleType.v1),
                new RuleVariant("います", "う", RuleType.None, RuleType.v5),
                new RuleVariant("きます", "く", RuleType.None, RuleType.v5),
                new RuleVariant("ぎます", "ぐ", RuleType.None, RuleType.v5),
                new RuleVariant("します", "す", RuleType.None, RuleType.v5),
                new RuleVariant("ちます", "つ", RuleType.None, RuleType.v5),
                new RuleVariant("にます", "ぬ", RuleType.None, RuleType.v5),
                new RuleVariant("びます", "ぶ", RuleType.None, RuleType.v5),
                new RuleVariant("みます", "む", RuleType.None, RuleType.v5),
                new RuleVariant("ります", "る", RuleType.None, RuleType.v5),
                new RuleVariant("じます", "ずる", RuleType.None, RuleType.vz),
                new RuleVariant("します", "する", RuleType.None, RuleType.vs),
                new RuleVariant("為ます", "為る", RuleType.None, RuleType.vs),
                new RuleVariant("きます", "くる", RuleType.None, RuleType.vk),
                new RuleVariant("来ます", "来る", RuleType.None, RuleType.vk),
                new RuleVariant("來ます", "來る", RuleType.None, RuleType.vk)
            ]),
            new Rule("polite negative", [
                new RuleVariant("くありません", "い", RuleType.None, RuleType.adji),
                new RuleVariant("ません", "る", RuleType.None, RuleType.v1),
                new RuleVariant("いません", "う", RuleType.None, RuleType.v5),
                new RuleVariant("きません", "く", RuleType.None, RuleType.v5),
                new RuleVariant("ぎません", "ぐ", RuleType.None, RuleType.v5),
                new RuleVariant("しません", "す", RuleType.None, RuleType.v5),
                new RuleVariant("ちません", "つ", RuleType.None, RuleType.v5),
                new RuleVariant("にません", "ぬ", RuleType.None, RuleType.v5),
                new RuleVariant("びません", "ぶ", RuleType.None, RuleType.v5),
                new RuleVariant("みません", "む", RuleType.None, RuleType.v5),
                new RuleVariant("りません", "る", RuleType.None, RuleType.v5),
                new RuleVariant("じません", "ずる", RuleType.None, RuleType.vz),
                new RuleVariant("しません", "する", RuleType.None, RuleType.vs),
                new RuleVariant("為ません", "為る", RuleType.None, RuleType.vs),
                new RuleVariant("きません", "くる", RuleType.None, RuleType.vk),
                new RuleVariant("来ません", "来る", RuleType.None, RuleType.vk),
                new RuleVariant("來ません", "來る", RuleType.None, RuleType.vk)
            ]),
            new Rule("polite past", [
                new RuleVariant("ました", "る", RuleType.None, RuleType.v1),
                new RuleVariant("いました", "う", RuleType.None, RuleType.v5),
                new RuleVariant("きました", "く", RuleType.None, RuleType.v5),
                new RuleVariant("ぎました", "ぐ", RuleType.None, RuleType.v5),
                new RuleVariant("しました", "す", RuleType.None, RuleType.v5),
                new RuleVariant("ちました", "つ", RuleType.None, RuleType.v5),
                new RuleVariant("にました", "ぬ", RuleType.None, RuleType.v5),
                new RuleVariant("びました", "ぶ", RuleType.None, RuleType.v5),
                new RuleVariant("みました", "む", RuleType.None, RuleType.v5),
                new RuleVariant("りました", "る", RuleType.None, RuleType.v5),
                new RuleVariant("じました", "ずる", RuleType.None, RuleType.vz),
                new RuleVariant("しました", "する", RuleType.None, RuleType.vs),
                new RuleVariant("為ました", "為る", RuleType.None, RuleType.vs),
                new RuleVariant("きました", "くる", RuleType.None, RuleType.vk),
                new RuleVariant("来ました", "来る", RuleType.None, RuleType.vk),
                new RuleVariant("來ました", "來る", RuleType.None, RuleType.vk)
            ]),
            new Rule("polite past negative", [
                new RuleVariant("くありませんでした", "い", RuleType.None, RuleType.adji),
                new RuleVariant("ませんでした", "る", RuleType.None, RuleType.v1),
                new RuleVariant("いませんでした", "う", RuleType.None, RuleType.v5),
                new RuleVariant("きませんでした", "く", RuleType.None, RuleType.v5),
                new RuleVariant("ぎませんでした", "ぐ", RuleType.None, RuleType.v5),
                new RuleVariant("しませんでした", "す", RuleType.None, RuleType.v5),
                new RuleVariant("ちませんでした", "つ", RuleType.None, RuleType.v5),
                new RuleVariant("にませんでした", "ぬ", RuleType.None, RuleType.v5),
                new RuleVariant("びませんでした", "ぶ", RuleType.None, RuleType.v5),
                new RuleVariant("みませんでした", "む", RuleType.None, RuleType.v5),
                new RuleVariant("りませんでした", "る", RuleType.None, RuleType.v5),
                new RuleVariant("じませんでした", "ずる", RuleType.None, RuleType.vz),
                new RuleVariant("しませんでした", "する", RuleType.None, RuleType.vs),
                new RuleVariant("為ませんでした", "為る", RuleType.None, RuleType.vs),
                new RuleVariant("きませんでした", "くる", RuleType.None, RuleType.vk),
                new RuleVariant("来ませんでした", "来る", RuleType.None, RuleType.vk),
                new RuleVariant("來ませんでした", "來る", RuleType.None, RuleType.vk)
            ]),
            new Rule("polite volitional", [
                new RuleVariant("ましょう", "る", RuleType.None, RuleType.v1),
                new RuleVariant("いましょう", "う", RuleType.None, RuleType.v5),
                new RuleVariant("きましょう", "く", RuleType.None, RuleType.v5),
                new RuleVariant("ぎましょう", "ぐ", RuleType.None, RuleType.v5),
                new RuleVariant("しましょう", "す", RuleType.None, RuleType.v5),
                new RuleVariant("ちましょう", "つ", RuleType.None, RuleType.v5),
                new RuleVariant("にましょう", "ぬ", RuleType.None, RuleType.v5),
                new RuleVariant("びましょう", "ぶ", RuleType.None, RuleType.v5),
                new RuleVariant("みましょう", "む", RuleType.None, RuleType.v5),
                new RuleVariant("りましょう", "る", RuleType.None, RuleType.v5),
                new RuleVariant("じましょう", "ずる", RuleType.None, RuleType.vz),
                new RuleVariant("しましょう", "する", RuleType.None, RuleType.vs),
                new RuleVariant("為ましょう", "為る", RuleType.None, RuleType.vs),
                new RuleVariant("きましょう", "くる", RuleType.None, RuleType.vk),
                new RuleVariant("来ましょう", "来る", RuleType.None, RuleType.vk),
                new RuleVariant("來ましょう", "來る", RuleType.None, RuleType.vk)
            ]),
            new Rule("potential", [
                new RuleVariant("れる", "る", RuleType.v1, RuleType.v1 | RuleType.v5),
                new RuleVariant("える", "う", RuleType.v1, RuleType.v5),
                new RuleVariant("ける", "く", RuleType.v1, RuleType.v5),
                new RuleVariant("げる", "ぐ", RuleType.v1, RuleType.v5),
                new RuleVariant("せる", "す", RuleType.v1, RuleType.v5),
                new RuleVariant("てる", "つ", RuleType.v1, RuleType.v5),
                new RuleVariant("ねる", "ぬ", RuleType.v1, RuleType.v5),
                new RuleVariant("べる", "ぶ", RuleType.v1, RuleType.v5),
                new RuleVariant("める", "む", RuleType.v1, RuleType.v5),
                new RuleVariant("これる", "くる", RuleType.v1, RuleType.vk),
                new RuleVariant("来れる", "来る", RuleType.v1, RuleType.vk),
                new RuleVariant("來れる", "來る", RuleType.v1, RuleType.vk)
            ]),
            new Rule("potential or passive", [
                new RuleVariant("られる", "る", RuleType.v1, RuleType.v1),
                new RuleVariant("ざれる", "ずる", RuleType.v1, RuleType.vz),
                new RuleVariant("ぜられる", "ずる", RuleType.v1, RuleType.vz),
                new RuleVariant("せられる", "する", RuleType.v1, RuleType.vs),
                new RuleVariant("為られる", "為る", RuleType.v1, RuleType.vs),
                new RuleVariant("こられる", "くる", RuleType.v1, RuleType.vk),
                new RuleVariant("来られる", "来る", RuleType.v1, RuleType.vk),
                new RuleVariant("來られる", "來る", RuleType.v1, RuleType.vk)
            ]),
            new Rule("volitional", [
                new RuleVariant("よう", "る", RuleType.None, RuleType.v1),
                new RuleVariant("おう", "う", RuleType.None, RuleType.v5),
                new RuleVariant("こう", "く", RuleType.None, RuleType.v5),
                new RuleVariant("ごう", "ぐ", RuleType.None, RuleType.v5),
                new RuleVariant("そう", "す", RuleType.None, RuleType.v5),
                new RuleVariant("とう", "つ", RuleType.None, RuleType.v5),
                new RuleVariant("のう", "ぬ", RuleType.None, RuleType.v5),
                new RuleVariant("ぼう", "ぶ", RuleType.None, RuleType.v5),
                new RuleVariant("もう", "む", RuleType.None, RuleType.v5),
                new RuleVariant("ろう", "る", RuleType.None, RuleType.v5),
                new RuleVariant("じよう", "ずる", RuleType.None, RuleType.vz),
                new RuleVariant("しよう", "する", RuleType.None, RuleType.vs),
                new RuleVariant("為よう", "為る", RuleType.None, RuleType.vs),
                new RuleVariant("こよう", "くる", RuleType.None, RuleType.vk),
                new RuleVariant("来よう", "来る", RuleType.None, RuleType.vk),
                new RuleVariant("來よう", "來る", RuleType.None, RuleType.vk)
            ]),
            new Rule("causative passive", [
                new RuleVariant("かされる", "く", RuleType.v1, RuleType.v5),
                new RuleVariant("がされる", "ぐ", RuleType.v1, RuleType.v5),
                new RuleVariant("たされる", "つ", RuleType.v1, RuleType.v5),
                new RuleVariant("なされる", "ぬ", RuleType.v1, RuleType.v5),
                new RuleVariant("ばされる", "ぶ", RuleType.v1, RuleType.v5),
                new RuleVariant("まされる", "む", RuleType.v1, RuleType.v5),
                new RuleVariant("らされる", "る", RuleType.v1, RuleType.v5),
                new RuleVariant("わされる", "う", RuleType.v1, RuleType.v5)
            ]),
            new Rule("-toku", [
                new RuleVariant("とく", "る", RuleType.v5, RuleType.v1),
                new RuleVariant("いとく", "く", RuleType.v5, RuleType.v5),
                new RuleVariant("いどく", "ぐ", RuleType.v5, RuleType.v5),
                new RuleVariant("しとく", "す", RuleType.v5, RuleType.v5),
                new RuleVariant("っとく", "う", RuleType.v5, RuleType.v5),
                new RuleVariant("っとく", "つ", RuleType.v5, RuleType.v5),
                new RuleVariant("っとく", "る", RuleType.v5, RuleType.v5),
                new RuleVariant("んどく", "ぬ", RuleType.v5, RuleType.v5),
                new RuleVariant("んどく", "ぶ", RuleType.v5, RuleType.v5),
                new RuleVariant("んどく", "む", RuleType.v5, RuleType.v5),
                new RuleVariant("じとく", "ずる", RuleType.v5, RuleType.vz),
                new RuleVariant("しとく", "する", RuleType.v5, RuleType.vs),
                new RuleVariant("為とく", "為る", RuleType.v5, RuleType.vs),
                new RuleVariant("きとく", "くる", RuleType.v5, RuleType.vk),
                new RuleVariant("来とく", "来る", RuleType.v5, RuleType.vk),
                new RuleVariant("來とく", "來る", RuleType.v5, RuleType.vk)
            ]),
            new Rule("progressive or perfect", [
                new RuleVariant("ている", "て", RuleType.v1, RuleType.iru),
                new RuleVariant("ておる", "て", RuleType.v5, RuleType.iru),
                new RuleVariant("てる", "て", RuleType.v1, RuleType.iru),
                new RuleVariant("でいる", "で", RuleType.v1, RuleType.iru),
                new RuleVariant("でおる", "で", RuleType.v5, RuleType.iru),
                new RuleVariant("でる", "で", RuleType.v1, RuleType.iru),
                new RuleVariant("とる", "て", RuleType.v5, RuleType.iru),
                new RuleVariant("ないでいる", "ない", RuleType.v1, RuleType.adji)
            ]),
            new Rule("-ki", [
                new RuleVariant("き", "い", RuleType.None, RuleType.adji)
            ]),
            new Rule("-ge", [
                new RuleVariant("しげ", "しい", RuleType.None, RuleType.adji)
            ]),
            new Rule("-e", [
                new RuleVariant("ねえ", "ない", RuleType.None, RuleType.adji),
                new RuleVariant("めえ", "むい", RuleType.None, RuleType.adji),
                new RuleVariant("みい", "むい", RuleType.None, RuleType.adji),
                new RuleVariant("ちぇえ", "つい", RuleType.None, RuleType.adji),
                new RuleVariant("ちい", "つい", RuleType.None, RuleType.adji),
                new RuleVariant("せえ", "すい", RuleType.None, RuleType.adji),
                new RuleVariant("ええ", "いい", RuleType.None, RuleType.adji),
                new RuleVariant("ええ", "わい", RuleType.None, RuleType.adji),
                new RuleVariant("ええ", "よい", RuleType.None, RuleType.adji),
                new RuleVariant("いぇえ", "よい", RuleType.None, RuleType.adji),
                new RuleVariant("うぇえ", "わい", RuleType.None, RuleType.adji),
                new RuleVariant("けえ", "かい", RuleType.None, RuleType.adji),
                new RuleVariant("げえ", "がい", RuleType.None, RuleType.adji),
                new RuleVariant("げえ", "ごい", RuleType.None, RuleType.adji),
                new RuleVariant("せえ", "さい", RuleType.None, RuleType.adji),
                new RuleVariant("めえ", "まい", RuleType.None, RuleType.adji),
                new RuleVariant("ぜえ", "ずい", RuleType.None, RuleType.adji),
                new RuleVariant("っぜえ", "ずい", RuleType.None, RuleType.adji),
                new RuleVariant("れえ", "らい", RuleType.None, RuleType.adji),
                new RuleVariant("れえ", "らい", RuleType.None, RuleType.adji),
                new RuleVariant("ちぇえ", "ちゃい", RuleType.None, RuleType.adji),
                new RuleVariant("でえ", "どい", RuleType.None, RuleType.adji),
                new RuleVariant("れえ", "れい", RuleType.None, RuleType.adji),
                new RuleVariant("べえ", "ばい", RuleType.None, RuleType.adji)
            ])
        ];
    }
}
